resolver: lts-14.27

packages:
- ./core
- ./server
- ./client
- ./docs
- ./examples
- ./test

extra-deps:
  - servant-0.17
  - servant-client-0.17
  - servant-client-core-0.17
  - servant-server-0.17
  - servant-docs-0.11.5
