# GENERATED HEADER START
name:                servant-websockets-server
version:             0.0.0.1
github:              "simspace/servant-websockets"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2019 SimSpace"
# GENERATED HEADER END

synopsis:            Server library for using websockets with servant

category:            Web

description:         Please see the README on GitHub at <https://github.com/estatico/servant-websockets#readme>

default-extensions:
- DataKinds
- AllowAmbiguousTypes
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies

dependencies:
- base
- resourcet
- servant-server
- servant-websockets-core
- wai-websockets
- websockets

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -O2
  - -eventlog
