# GENERATED HEADER START
name:                servant-websockets-examples
version:             0.0.0.1
github:              "simspace/servant-websockets"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2019 SimSpace"
# GENERATED HEADER END

synopsis:            Example server and client for servant-websockets

category:            Web

description:         Please see the README on GitHub at <https://github.com/estatico/servant-websockets#readme>

default-extensions:
- DataKinds
- DeriveGeneric
- DerivingStrategies
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
- TypeOperators

dependencies:
- base
- http-client
- servant
- servant-client
- servant-client-core
- servant-server
- servant-websockets-client
- servant-websockets-core
- servant-websockets-server
- text
- warp
- websockets

library:
  ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -O0
  - -eventlog
  source-dirs:
  - src

executables:
  servant-websocket-example:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-websockets-examples
